[package]
name = "rayhem"
version = "0.3.0"
authors = ["Mako <jlauve@rsmw.net>"]

[dependencies]
cgmath = "0.12.0"
rand = "0.3.15"
specs = "0.7.1"
time = "*"

[dependencies.sdl2]
version = "0.29"
features = ["image"]
